# Generated by Django 2.2.24 on 2021-11-24 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='mytimetable',
            name='age',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
