# Generated by Django 2.2.24 on 2021-11-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20211124_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mytimetable',
        ),
    ]
