# Generated by Django 2.2.24 on 2021-11-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20211125_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
