# Generated by Django 2.2.24 on 2021-11-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20211127_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
