# Generated by Django 2.2.24 on 2021-11-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_table_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
