# Generated by Django 2.2.24 on 2021-11-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_delete_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='age',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('cabinet', models.IntegerField()),
                ('teacher', models.CharField(max_length=40)),
                ('lesson', models.CharField(max_length=40)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Group')),
            ],
        ),
    ]
