# Generated by Django 2.2.24 on 2021-11-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
