# Generated by Django 2.2.24 on 2021-11-29 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('week', models.CharField(max_length=30)),
                ('cabinet', models.IntegerField()),
                ('teacher', models.CharField(max_length=40)),
                ('lesson', models.CharField(max_length=40)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Group')),
            ],
        ),
    ]
