# Generated by Django 2.2.24 on 2021-12-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0020_auto_20211202_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
    ]
