# Generated by Django 2.2.24 on 2021-12-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_cabinets_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
