# Generated by Django 2.2.24 on 2021-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('day_of_week', models.CharField(max_length=30)),
                ('cabinet', models.IntegerField()),
                ('group', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=40)),
                ('teacher', models.CharField(max_length=40)),
                ('lesson', models.CharField(max_length=40)),
            ],
        ),
    ]
