# Generated by Django 2.2.24 on 2021-12-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='age',
        ),
        migrations.AlterField(
            model_name='table',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Group'),
        ),
    ]
